# -*- coding: utf-8 -*-
"""Streamlit + Colab wit pyngrok

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/amrrs/streamlit-colab-pyngrok/blob/main/Streamlit_%2B_Colab_wit_pyngrok.ipynb
"""

! pip install streamlit -q

"""Write the cell python code into an app.py file"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# st.write("Find Odd or Even - Snehith M")
# def user_input():
#   number = st.number_input("Give a number",step=1)
#   return number
# df = user_input()  
# if df%2==0:
#   st.write("Even")
# else:
#   st.write("Odd")

! pip install pyngrok

from pyngrok import ngrok

"""ngrok config add-authtoken 2HvyPNAtlva3TThlHYQfuXb5Gov_uSzEPWrpfs3Taq96Y72u"""

ngrok.set_auth_token("2HvyPNAtlva3TThlHYQfuXb5Gov_uSzEPWrpfs3Taq96Y72u") #ngrok.com

!nohup streamlit run app.py --server.port 80 &
url = ngrok.connect(port = '80')
print(url)

from pyngrok import ngrok

tunnels = ngrok.get_tunnels()
tunnels

# try:
#     # Block until CTRL-C or some other terminating event
#     ngrok_process.proc.wait()
# except KeyboardInterrupt:
#     print(" Shutting down server.")

#     ngrok.kill()

"""Run streamlit using `localtunnel` 

npm installation would take some time for the first time
"""

